version: "3.4"

services:
  dataapi:
    image: dataapi
    volumes:
      - ./:/code
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
